services:
  web:
    build: .
    container_name: task-manager-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: task_user
      DB_NAME: task_db
      DB_PASSWORD: "123"
      GEMINI_API_KEY: "AIzaSyBJnFPDXiHlMelJvfb9gdOJkET9fDxz_TE"
      SECRET_KEY: "dev-secret-key"
    ports:
      - "5000:5000"

  db:
    image: mysql:8
    container_name: task-manager-db
    restart: always
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: "123"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: task-manager-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
